CREATE TABLE POIs (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    Address TEXT,
    Latitude DOUBLE PRECISION,
    Longitude DOUBLE PRECISION,
    Radius INT,
    ImageUrl TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Restaurant_Details (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PoiId INT,
    OpeningHours VARCHAR(255),
    Phone VARCHAR(50),
    FOREIGN KEY (PoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Restaurant_Audio (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PoiId INT,
    LanguageCode VARCHAR(10),
    AudioUrl TEXT,
    FOREIGN KEY (PoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Foods (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PoiId INT,
    Name VARCHAR(255),
    Description TEXT,
    Price NUMERIC(10,2),
    ImageUrl TEXT,
    FOREIGN KEY (PoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Owner_Requests (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PoiId INT,
    RequestType VARCHAR(100),
    Content TEXT,
    Status VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Device_Visits (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DeviceId VARCHAR(100),
    PoiId INT,
    EnterTime TIMESTAMP,
    ExitTime TIMESTAMP,
    Duration INT,
    FOREIGN KEY (PoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Location_Logs (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DeviceId VARCHAR(100),
    Latitude DOUBLE PRECISION,
    Longitude DOUBLE PRECISION,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Movement_Paths (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DeviceId VARCHAR(100),
    FromPoiId INT,
    ToPoiId INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FromPoiId) REFERENCES POIs(Id) ON DELETE CASCADE,
    FOREIGN KEY (ToPoiId) REFERENCES POIs(Id) ON DELETE CASCADE
);

CREATE TABLE Admins (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR(100),
    PasswordHash TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);